services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ioms
      POSTGRES_USER: ioms
      POSTGRES_PASSWORD: ioms
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
